routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductosController;
use App\Http\Controllers\VentasController;
use App\Http\Controllers\VentasaController;
use App\Http\Controllers\VentaseController;
use App\Http\Controllers\VentasfeController;
use App\Http\Controllers\VentasmarController;
use App\Http\Controllers\VentasmayController;
use App\Http\Controllers\VentasjunController;
use App\Http\Controllers\VentasjulController;

use App\Http\Controllers\VentassepController;
use App\Http\Controllers\VentasoctController;
use App\Http\Controllers\VentasnovController;
use App\Http\Controllers\VentasdicController;
use App\Http\Controllers\VentasagoController;



use App\Http\Controllers\CatalogoController;
use App\Models\Ventas;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('inicio');
    
})->name('inicio');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    $ventas=Ventas::all();
    return view('dashboard',compact('ventas'));
})->name('perfil');

Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventas', VentasController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasa', VentasaController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventase', VentaseController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasfe', VentasfeController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasmar', VentasmarController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasmay', VentasmayController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasjun', VentasjunController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasjul', VentasjulController::class);

Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasago', VentasagoController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventassep', VentassepController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasoct', VentasoctController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasnov', VentasnovController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('ventasdic', VentasdicController::class);




Route::view('acerca de', 'about')->name('about');
Route::resource('catalogo', CatalogoController::class);
Route::middleware(['auth:sanctum', 'verified' , 'admin'])->resource('productos', ProductosController::class);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/agregar_producto.blade.php
<x-app-layout>



    @section('Titulo')
PaperWeb
@endsection





@section('contenido')



        <h1 class="d-flex justify-content-center mt-1">REGISTRO ARTICULOS</h1>

<form class="mb-3" action="{{ route('productos.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Nombre</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="nombre" placeholder="Ingrese su producto" value="{{ old('nombre') }}" required/>
    </div>

    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Descripcion</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="descripcion" placeholder="Ingrese descripcion" value="{{ old('descripcion') }}" required/>
    </div>

    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Categoria</label>        
    <input type="text" class="form-control bg-dark-x border-0" name="categoria" placeholder="Ingrese categoria" value="{{ old('categoria') }}" required/>
    </div>

    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Precio</label>   
    <input type="number" class="form-control bg-dark-x border-0" name="precio" placeholder="Ingrese el precio" value="{{ old('precio') }}" required/>
    </div>


    <div class="">
        <label for="exampleInputEmail1" class="form-label font-weight-bold">Cantidad</label>   
        <input type="number" class="form-control bg-dark-x border-0" name="cantidad" placeholder="Ingrese cantidad" value="{{ old('cantidad') }}" required/>
        </div>

    <div class="">
        <label for="formFile" class="form-label">Ingrese su foto</label>
        <input class="form-control" type="file" name="imagen" required>
        </div>

    <div class="d-flex justify-content-center">
    <button type="submit" class="btn btn-warning w-100 ">Enviar</button>
</div>
</form>


@endsection

</x-app-layout>

resources/views/detalle_producto.blade.php
<x-app-layout>



    @section('Titulo')
    PaperWeb
@endsection





@section('contenido')


<div class=" p-1 mt-3"> 
  <h2 class="text-center m-0">Especificaciones</h2>
  </div>
  <div class="bg-warning p-1 mt-1"> 
    <h1 class="text-center m-0 text-light"></h1>
    </div>


<!-- Header -->
<div class="card mb-3">
  <div class="row justify-content-center">
  <div class="col-6">
    <div class="row justify-content-center">
  <div class="col-6">
  <img src="{{asset('storage/'.$producto->imagen)}}" class="card-img" alt="..." height="200px" width="200px">
  </div>
    </div>
  
  <div class="card-body">
    <h5 class="card-title">Articulo: {{ $producto->nombre}}</h5>
    <p class="card-text">Descripcion: {{ $producto->descripcion}}</p>
    <p class="card-text">Precio: {{ $producto->precio}}</p>
    <p class="card-text">Cantidad: {{ $producto->cantidad}}</p>
    <p class="card-text">Tipo: {{ $producto->categoria}}</p>
    <p class="card-text"><small class="text-muted">Ultima actualizacion {{$producto->updated_at}}</small></p>
  </div>
</div>
</div>

@endsection

</x-app-layout>

resources/views/editar_producto.blade.php
<x-app-layout>
    @section('Titulo')
    PaperWeb
@endsection





@section('contenido')


<h1 class="d-flex justify-content-center mt-1">ACTUALIZAR ARTICULOS</h1>
  <form class="mb-3" action="{{ route('productos.update', $producto->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Nombre</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="nombre" placeholder="Ingrese su producto" value="{{$producto->nombre}}" required/>
    </div>

    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Descripcion</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="descripcion" placeholder="Ingrese descripcion" value="{{$producto->descripcion}}" required/>
    </div>


   
    <div class="">
      <label for="exampleInputEmail1" class="form-label font-weight-bold">Tipo</label>
      <input type="text" class="form-control bg-dark-x border-0" name="categoria" placeholder="Ingrese descripcion" value="{{$producto->categoria}}" required/>
    </div>

    <div class="">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Precio</label>   
    <input type="number" class="form-control bg-dark-x border-0" name="precio" placeholder="Ingrese el precio" value="{{$producto->precio}}" required/>
    </div>


    <div class="">
        <label for="exampleInputEmail1" class="form-label font-weight-bold">Cantidad</label>   
        <input type="number" class="form-control bg-dark-x border-0" name="cantidad" placeholder="Ingrese cantidad" value="{{$producto->cantidad}}" required/>
        </div>

    <div class="">
        <label for="formFile" class="form-label">Ingrese su foto</label>
        <input class="form-control" type="file" name="imagen" required>
        </div>

    <div class="d-flex justify-content-center">
    <button type="submit" class="btn btn-warning w-100 ">Enviar</button>
</div>
</form>


@endsection
       
</x-app-layout>

resources/views/lista_productos.blade.php
<x-app-layout>



    @section('Titulo')
    PaperWeb
@endsection





@section('contenido')

<div class=" p-3 mt-2"> 
    <h3 class="text-center m-0 ">Lista de Productos</h3>
    </div>






    <a href="{{route('productos.create')}}" class="btn btn-warning mt-3" ><i class="fas fa-plus-circle"></i></a>
    

    
    @if(session()->has('mensaje'))
    <p style="color: rgb(12, 59, 146)">{{ session('mensaje') }}</p>
    @endif





    
    <table class="table  mt-2" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Nombre</th>
              <th scope="col">Costo</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Imagen</th>

              
              <th scope="col" class="text-center">Opciones</th>
              
            </tr>
          </thead>



        @foreach ($productos as $productos)
        <tbody>    
            <tr>
                


                <td>{{ $productos->nombre }}</td>
                
                <td>{{ $productos->precio }}</td>
                <td>{{ $productos->cantidad }}</td>
                <td><img src="{{asset('storage/'.$productos->imagen)}}" 
                     alt="..." width="50px" height="50px"></td>
                
                    

                <td>
                    <div class="d-flex justify-content-center">
                <a href="{{ route('productos.show', $productos->id)}}" class="btn  btn-primary active mx-1 d-inline ">ver</a>
                <a href="{{ route('productos.edit', $productos->id)}}" class="btn  btn-primary active mx-1 d-inline">editar</i></a>
                
                    <form action="{{ route('productos.destroy', $productos->id) }}" method="post" class="d-inline mx-1">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary active">borrar</button>
                    </form>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
 


    
    
    

@endsection

</x-app-layout>

resources/views/user.blade.php
<x-app-layout>
    @section('Titulo')
PaperWeb
@endsection

@section('estilo')
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
@endsection



@section('contenido')

<main>
    {{ $slot }}
</main>
</div>
@stack('modals')
@livewireScripts

@endsection








            
</x-app-layout>

resources/views/ventas.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">TODAS LAS COMPRAS</h1>
        </div>
    <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>

    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventasa.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS ABRIL</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventasago.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS AGOSTO</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventase.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS ENERO</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventasmar.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS MARZO</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventasnov.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS NOVIEMBRE</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>

resources/views/ventassep.blade.php
<x-app-layout>

    @section('Titulo')
    PaperWeb
    @endsection
    
    
    
    
    
    @section('contenido')
    <div class=" p-3 mt-4"> 
        <h1 class="text-center m-0 ">COMPRAS SEPTIEMBRE</h1>
        </div>
        <a href="{{route('ventase.index')}}" class="btn btn-warning mt-3" >Enero</a>
    <a href="{{route('ventasfe.index')}}" class="btn btn-warning mt-3" >Febrero</a>
    <a href="{{route('ventasmar.index')}}" class="btn btn-warning mt-3" >Marzo</a>
    <a href="{{route('ventasa.index')}}" class="btn btn-warning mt-3" >Abril</a>
    <a href="{{route('ventasmay.index')}}" class="btn btn-warning mt-3" >Mayo</a>
    <a href="{{route('ventasjun.index')}}" class="btn btn-warning mt-3" >Junio</a>
    <a href="{{route('ventasjul.index')}}" class="btn btn-warning mt-3" >Julio</a>
    <a href="{{route('ventasago.index')}}" class="btn btn-warning mt-3" >Agosto</a>
    <a href="{{route('ventassep.index')}}" class="btn btn-warning mt-3" >Septiembre</a>
    <a href="{{route('ventasoct.index')}}" class="btn btn-warning mt-3" >Octubre</a>
    <a href="{{route('ventasnov.index')}}" class="btn btn-warning mt-3" >Noviembre</a>
    <a href="{{route('ventasdic.index')}}" class="btn btn-warning mt-3" >Diciembre</a>
    <a href="{{route('ventas.index')}}" class="btn btn-danger mt-3" >Todas</a>
    
    <table class="table  mt-4" id="data" class="display">
        <thead class="table-Light">
            <tr>
              <th scope="col">Articulo</th>
              <th scope="col">Cliente</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Costo</th>
              <th scope="col">Fecha</th>
              
              
    
            
              
            </tr>
          </thead>
    
    
          
        @foreach ($ventas as $ventas)
    
    
        
        <tbody>   
            
            <tr>
                <td>{{ $ventas->productos }}</td>
                <td>{{ $ventas->clientenomb }}</td>
                <td>{{ $ventas->cantidad }}</td>
                <td>{{ $ventas->coste }}</td>
                <td>{{ $ventas->created_at }}</td>
            </tr>
            
            
            
        @endforeach
    
        
    </table>
    
    @endsection
    
    </x-app-layout>